-- MySQL integration test tables for FlexDBLink

DROP TABLE IF EXISTS IT_TYPED_AUX;
DROP TABLE IF EXISTS IT_TYPED_MAIN;

CREATE TABLE IT_TYPED_MAIN (
  ID             BIGINT PRIMARY KEY,
  VC_COL         VARCHAR(200),
  CHAR_COL       CHAR(10),
  NVC_COL        VARCHAR(200),
  NCHAR_COL      CHAR(10),

  ENUM_COL       ENUM('alpha','beta','gamma'),
  SET_COL        SET('A','B','C'),
  JSON_COL       JSON,

  TINYINT_COL    TINYINT,
  SMALLINT_COL   SMALLINT,
  MEDIUMINT_COL  MEDIUMINT,
  INT_COL        INT,
  BIGINT_COL2    BIGINT,
  NUM_COL        DECIMAL(20, 6),
  BF_COL         FLOAT,
  BD_COL         DOUBLE,
  BIT_COL        BIT(8),
  BOOL_COL       BOOLEAN,

  YEAR_COL       YEAR,
  DATE_COL       DATE,
  TIME_COL       TIME,
  TS_COL         DATETIME(6),
  TSTZ_COL       TIMESTAMP(6) NULL,

  RAW_COL        VARBINARY(32),
  BINARY_COL     BINARY(4),
  VARBIN_COL     VARBINARY(32),

  XML_COL        LONGTEXT,
  TINYTEXT_COL   TINYTEXT,
  MEDIUMTEXT_COL MEDIUMTEXT,
  LONGTEXT_COL   LONGTEXT,
  CLOB_COL       TEXT,
  NCLOB_COL      TEXT,

  TINYBLOB_COL   TINYBLOB,
  MEDIUMBLOB_COL MEDIUMBLOB,
  LONGBLOB_COL   LONGBLOB,
  BLOB_COL       BLOB,

  LOB_KIND       VARCHAR(30)
);

CREATE TABLE IT_TYPED_AUX (
  ID             BIGINT PRIMARY KEY,
  MAIN_ID        BIGINT NOT NULL,
  LABEL          VARCHAR(200),
  PAYLOAD_XML    LONGTEXT,
  PAYLOAD_JSON   JSON,
  PAYLOAD_CLOB   TEXT,
  PAYLOAD_BLOB   BLOB,
  LOB_KIND       VARCHAR(30)
);
