-- FlexAssert integration test tables for PostgreSQL

DROP TABLE IF EXISTS FA_CHILD_H;
DROP TABLE IF EXISTS FA_PARENT_H;
DROP TABLE IF EXISTS FA_GRANDPARENT;
DROP TABLE IF EXISTS FA_CHILD;
DROP TABLE IF EXISTS FA_PARENT;
DROP TABLE IF EXISTS FA_COMPOSITE_PK;
DROP TABLE IF EXISTS FA_LOB;
DROP TABLE IF EXISTS FA_NULLABLE;
DROP TABLE IF EXISTS FA_SIMPLE;

CREATE TABLE FA_SIMPLE (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  VALUE       NUMERIC(10,2),
  FLAG        BOOLEAN,
  CREATED_AT  TIMESTAMP
);

CREATE TABLE FA_NULLABLE (
  ID          BIGINT PRIMARY KEY,
  STR_COL     VARCHAR(200),
  NUM_COL     NUMERIC(20,6),
  DATE_COL    DATE,
  TIME_COL    TIME,
  TS_COL      TIMESTAMP
);

CREATE TABLE FA_LOB (
  ID          BIGINT PRIMARY KEY,
  LABEL       VARCHAR(100),
  CLOB_COL    TEXT,
  BLOB_COL    BYTEA,
  LOB_KIND    VARCHAR(30)
);

CREATE TABLE FA_PARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  STATUS      VARCHAR(20)
);

CREATE TABLE FA_CHILD (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL REFERENCES FA_PARENT(ID),
  LABEL       VARCHAR(100),
  AMOUNT      NUMERIC(10,2)
);

CREATE TABLE FA_GRANDPARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL
);

CREATE TABLE FA_PARENT_H (
  ID              BIGINT PRIMARY KEY,
  GRANDPARENT_ID  BIGINT NOT NULL REFERENCES FA_GRANDPARENT(ID),
  NAME            VARCHAR(100)
);

CREATE TABLE FA_CHILD_H (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL REFERENCES FA_PARENT_H(ID),
  VALUE       VARCHAR(200)
);

CREATE TABLE FA_COMPOSITE_PK (
  REGION      VARCHAR(10) NOT NULL,
  SEQ         BIGINT NOT NULL,
  DESCRIPTION VARCHAR(200),
  PRIMARY KEY (REGION, SEQ)
);
