CREATE TABLE IT_FK_ROOT (
  ID BIGINT PRIMARY KEY,
  LABEL NVARCHAR(100)
);

CREATE TABLE IT_FK_CHILD (
  ID BIGINT PRIMARY KEY,
  ROOT_ID BIGINT NOT NULL,
  LABEL NVARCHAR(100)
);

CREATE TABLE IT_FK_GRANDCHILD (
  ID BIGINT PRIMARY KEY,
  CHILD_ID BIGINT NOT NULL,
  LABEL NVARCHAR(100)
);

CREATE TABLE IT_FK_GREATGRANDCHILD (
  ID BIGINT PRIMARY KEY,
  GRANDCHILD_ID BIGINT NOT NULL,
  LABEL NVARCHAR(100)
);

ALTER TABLE IT_FK_CHILD ADD CONSTRAINT FK_ITFK_CHILD_ROOT
FOREIGN KEY (ROOT_ID) REFERENCES IT_FK_ROOT(ID);

ALTER TABLE IT_FK_GRANDCHILD ADD CONSTRAINT FK_ITFK_GRAND_CHILD
FOREIGN KEY (CHILD_ID) REFERENCES IT_FK_CHILD(ID);

ALTER TABLE IT_FK_GREATGRANDCHILD ADD CONSTRAINT FK_ITFK_GREAT_GRAND
FOREIGN KEY (GRANDCHILD_ID) REFERENCES IT_FK_GRANDCHILD(ID);
