-- PostgreSQL integration test tables for FlexDBLink

DROP TABLE IF EXISTS IT_TYPED_AUX;
DROP TABLE IF EXISTS IT_TYPED_MAIN;

CREATE TABLE IT_TYPED_MAIN (
  ID            BIGINT PRIMARY KEY,
  VC_COL        VARCHAR(200),
  CHAR_COL      CHAR(10),
  NVC_COL       VARCHAR(200),
  NCHAR_COL     CHAR(10),

  NUM_COL       NUMERIC(20, 6),
  BF_COL        REAL,
  BD_COL        DOUBLE PRECISION,

  DATE_COL      DATE,
  TIME_COL      TIME,
  TS_COL        TIMESTAMP,
  TSTZ_COL      TIMESTAMPTZ,

  RAW_COL       BYTEA,
  XML_COL       XML,

  CLOB_COL      TEXT,
  NCLOB_COL     TEXT,
  BLOB_COL      BYTEA,

  LOB_KIND      VARCHAR(30)
);

CREATE TABLE IT_TYPED_AUX (
  ID            BIGINT PRIMARY KEY,
  MAIN_ID       BIGINT NOT NULL,
  LABEL         VARCHAR(200),
  PAYLOAD_XML   XML,

  PAYLOAD_CLOB  TEXT,
  PAYLOAD_BLOB  BYTEA,

  LOB_KIND      VARCHAR(30)
);
