-- SQL Server integration test tables for FlexDBLink

IF OBJECT_ID('IT_TYPED_AUX', 'U') IS NOT NULL DROP TABLE IT_TYPED_AUX;
IF OBJECT_ID('IT_TYPED_MAIN', 'U') IS NOT NULL DROP TABLE IT_TYPED_MAIN;

CREATE TABLE IT_TYPED_MAIN (
  ID            BIGINT PRIMARY KEY,
  VC_COL        VARCHAR(200),
  CHAR_COL      CHAR(10),
  NVC_COL       NVARCHAR(200),
  NCHAR_COL     NCHAR(10),

  NUM_COL       NUMERIC(20, 6),
  BF_COL        REAL,
  BD_COL        FLOAT,

  DATE_COL      DATE,
  TIME_COL      TIME,
  TS_COL        DATETIME2,
  TSTZ_COL      DATETIMEOFFSET NULL,

  RAW_COL       VARBINARY(32),
  XML_COL       XML,

  CLOB_COL      VARCHAR(MAX),
  NCLOB_COL     NVARCHAR(MAX),
  BLOB_COL      VARBINARY(MAX),

  LOB_KIND      VARCHAR(30)
);

CREATE TABLE IT_TYPED_AUX (
  ID            BIGINT PRIMARY KEY,
  MAIN_ID       BIGINT NOT NULL,
  LABEL         VARCHAR(200),
  PAYLOAD_XML   XML,

  PAYLOAD_CLOB  VARCHAR(MAX),
  PAYLOAD_BLOB  VARBINARY(MAX),

  LOB_KIND      VARCHAR(30)
);
