-- FlexAssert integration test tables for SQL Server

IF OBJECT_ID('FA_CHILD_H', 'U') IS NOT NULL DROP TABLE FA_CHILD_H;
IF OBJECT_ID('FA_PARENT_H', 'U') IS NOT NULL DROP TABLE FA_PARENT_H;
IF OBJECT_ID('FA_GRANDPARENT', 'U') IS NOT NULL DROP TABLE FA_GRANDPARENT;
IF OBJECT_ID('FA_CHILD', 'U') IS NOT NULL DROP TABLE FA_CHILD;
IF OBJECT_ID('FA_PARENT', 'U') IS NOT NULL DROP TABLE FA_PARENT;
IF OBJECT_ID('FA_COMPOSITE_PK', 'U') IS NOT NULL DROP TABLE FA_COMPOSITE_PK;
IF OBJECT_ID('FA_LOB', 'U') IS NOT NULL DROP TABLE FA_LOB;
IF OBJECT_ID('FA_NULLABLE', 'U') IS NOT NULL DROP TABLE FA_NULLABLE;
IF OBJECT_ID('FA_SIMPLE', 'U') IS NOT NULL DROP TABLE FA_SIMPLE;

CREATE TABLE FA_SIMPLE (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  VALUE       DECIMAL(10,2),
  FLAG        BIT,
  CREATED_AT  DATETIME2
);

CREATE TABLE FA_NULLABLE (
  ID          BIGINT PRIMARY KEY,
  STR_COL     VARCHAR(200),
  NUM_COL     DECIMAL(20,6),
  DATE_COL    DATE,
  TIME_COL    TIME,
  TS_COL      DATETIME2
);

CREATE TABLE FA_LOB (
  ID          BIGINT PRIMARY KEY,
  LABEL       VARCHAR(100),
  CLOB_COL    VARCHAR(MAX),
  BLOB_COL    VARBINARY(MAX),
  LOB_KIND    VARCHAR(30)
);

CREATE TABLE FA_PARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  STATUS      VARCHAR(20)
);

CREATE TABLE FA_CHILD (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL REFERENCES FA_PARENT(ID),
  LABEL       VARCHAR(100),
  AMOUNT      DECIMAL(10,2)
);

CREATE TABLE FA_GRANDPARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL
);

CREATE TABLE FA_PARENT_H (
  ID              BIGINT PRIMARY KEY,
  GRANDPARENT_ID  BIGINT NOT NULL REFERENCES FA_GRANDPARENT(ID),
  NAME            VARCHAR(100)
);

CREATE TABLE FA_CHILD_H (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL REFERENCES FA_PARENT_H(ID),
  VALUE       VARCHAR(200)
);

CREATE TABLE FA_COMPOSITE_PK (
  REGION      VARCHAR(10) NOT NULL,
  SEQ         BIGINT NOT NULL,
  DESCRIPTION VARCHAR(200),
  PRIMARY KEY (REGION, SEQ)
);
