CREATE TABLE IT_FK_ROOT (
  ID NUMBER(10) PRIMARY KEY,
  LABEL VARCHAR2(100)
)
/

CREATE TABLE IT_FK_CHILD (
  ID NUMBER(10) PRIMARY KEY,
  ROOT_ID NUMBER(10) NOT NULL,
  LABEL VARCHAR2(100)
)
/

CREATE TABLE IT_FK_GRANDCHILD (
  ID NUMBER(10) PRIMARY KEY,
  CHILD_ID NUMBER(10) NOT NULL,
  LABEL VARCHAR2(100)
)
/

CREATE TABLE IT_FK_GREATGRANDCHILD (
  ID NUMBER(10) PRIMARY KEY,
  GRANDCHILD_ID NUMBER(10) NOT NULL,
  LABEL VARCHAR2(100)
)
/

ALTER TABLE IT_FK_CHILD ADD CONSTRAINT FK_ITFK_CHILD_ROOT
FOREIGN KEY (ROOT_ID) REFERENCES IT_FK_ROOT(ID)
/

ALTER TABLE IT_FK_GRANDCHILD ADD CONSTRAINT FK_ITFK_GRAND_CHILD
FOREIGN KEY (CHILD_ID) REFERENCES IT_FK_CHILD(ID)
/

ALTER TABLE IT_FK_GREATGRANDCHILD ADD CONSTRAINT FK_ITFK_GREAT_GRAND
FOREIGN KEY (GRANDCHILD_ID) REFERENCES IT_FK_GRANDCHILD(ID)
/
