-- FlexAssert integration test tables for Oracle

BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_CHILD_H CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_PARENT_H CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_GRANDPARENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_CHILD CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_PARENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_COMPOSITE_PK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_LOB CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_NULLABLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FA_SIMPLE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE FA_SIMPLE (
  ID          NUMBER(19) PRIMARY KEY,
  NAME        VARCHAR2(100) NOT NULL,
  VALUE       NUMBER(10,2),
  FLAG        NUMBER(1),
  CREATED_AT  TIMESTAMP
);

CREATE TABLE FA_NULLABLE (
  ID          NUMBER(19) PRIMARY KEY,
  STR_COL     VARCHAR2(200),
  NUM_COL     NUMBER(20,6),
  DATE_COL    DATE,
  TIME_COL    TIMESTAMP,
  TS_COL      TIMESTAMP
);

CREATE TABLE FA_LOB (
  ID          NUMBER(19) PRIMARY KEY,
  LABEL       VARCHAR2(100),
  CLOB_COL    CLOB,
  BLOB_COL    BLOB,
  LOB_KIND    VARCHAR2(30)
);

CREATE TABLE FA_PARENT (
  ID          NUMBER(19) PRIMARY KEY,
  NAME        VARCHAR2(100) NOT NULL,
  STATUS      VARCHAR2(20)
);

CREATE TABLE FA_CHILD (
  ID          NUMBER(19) PRIMARY KEY,
  PARENT_ID   NUMBER(19) NOT NULL REFERENCES FA_PARENT(ID),
  LABEL       VARCHAR2(100),
  AMOUNT      NUMBER(10,2)
);

CREATE TABLE FA_GRANDPARENT (
  ID          NUMBER(19) PRIMARY KEY,
  NAME        VARCHAR2(100) NOT NULL
);

CREATE TABLE FA_PARENT_H (
  ID              NUMBER(19) PRIMARY KEY,
  GRANDPARENT_ID  NUMBER(19) NOT NULL REFERENCES FA_GRANDPARENT(ID),
  NAME            VARCHAR2(100)
);

CREATE TABLE FA_CHILD_H (
  ID          NUMBER(19) PRIMARY KEY,
  PARENT_ID   NUMBER(19) NOT NULL REFERENCES FA_PARENT_H(ID),
  VALUE       VARCHAR2(200)
);

CREATE TABLE FA_COMPOSITE_PK (
  REGION      VARCHAR2(10) NOT NULL,
  SEQ         NUMBER(19) NOT NULL,
  DESCRIPTION VARCHAR2(200),
  PRIMARY KEY (REGION, SEQ)
);
