INSERT INTO IT_TYPED_MAIN (ID, VC_COL, CHAR_COL, NVC_COL, NCHAR_COL, CLOB_COL, NCLOB_COL,
  BLOB_COL, LOB_KIND)
VALUES (99, NULL, NULL, NULL, NULL, EMPTY_CLOB(), NULL, EMPTY_BLOB(), 'empty')
/

INSERT INTO IT_TYPED_AUX (ID, MAIN_ID, LABEL, PAYLOAD_CLOB, PAYLOAD_BLOB, LOB_KIND)
VALUES (99, 99, NULL, EMPTY_CLOB(), NULL, 'empty')
/
