CREATE TABLE IT_TYPED_MAIN (
  ID NUMBER(10) PRIMARY KEY,
  VC_COL VARCHAR2(100),
  CHAR_COL CHAR(10),
  NVC_COL NVARCHAR2(100),
  NCHAR_COL NCHAR(20),
  NUM_COL NUMBER(18,4),
  BF_COL BINARY_FLOAT,
  BD_COL BINARY_DOUBLE,
  DATE_COL DATE,
  TS_COL TIMESTAMP(6),
  TSTZ_COL TIMESTAMP(6) WITH TIME ZONE,
  TSLTZ_COL TIMESTAMP(6) WITH LOCAL TIME ZONE,
  IV_YM_COL INTERVAL YEAR(2) TO MONTH,
  IV_DS_COL INTERVAL DAY(2) TO SECOND(0),
  RAW_COL RAW(64),
  CLOB_COL CLOB,
  NCLOB_COL NCLOB,
  BLOB_COL BLOB,
  LOB_KIND VARCHAR2(30)
)
/

CREATE TABLE IT_TYPED_AUX (
  ID NUMBER(10) PRIMARY KEY,
  MAIN_ID NUMBER(10),
  LABEL VARCHAR2(100),
  PAYLOAD_CLOB CLOB,
  PAYLOAD_BLOB BLOB,
  LOB_KIND VARCHAR2(30)
)
/
