-- FlexAssert integration test tables for MySQL

DROP TABLE IF EXISTS FA_CHILD_H;
DROP TABLE IF EXISTS FA_PARENT_H;
DROP TABLE IF EXISTS FA_GRANDPARENT;
DROP TABLE IF EXISTS FA_CHILD;
DROP TABLE IF EXISTS FA_PARENT;
DROP TABLE IF EXISTS FA_COMPOSITE_PK;
DROP TABLE IF EXISTS FA_LOB;
DROP TABLE IF EXISTS FA_NULLABLE;
DROP TABLE IF EXISTS FA_SIMPLE;

CREATE TABLE FA_SIMPLE (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  VALUE       DECIMAL(10,2),
  FLAG        BOOLEAN,
  CREATED_AT  DATETIME
) ENGINE=InnoDB;

CREATE TABLE FA_NULLABLE (
  ID          BIGINT PRIMARY KEY,
  STR_COL     VARCHAR(200),
  NUM_COL     DECIMAL(20,6),
  DATE_COL    DATE,
  TIME_COL    TIME,
  TS_COL      DATETIME
) ENGINE=InnoDB;

CREATE TABLE FA_LOB (
  ID          BIGINT PRIMARY KEY,
  LABEL       VARCHAR(100),
  CLOB_COL    LONGTEXT,
  BLOB_COL    LONGBLOB,
  LOB_KIND    VARCHAR(30)
) ENGINE=InnoDB;

CREATE TABLE FA_PARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL,
  STATUS      VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE FA_CHILD (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL,
  LABEL       VARCHAR(100),
  AMOUNT      DECIMAL(10,2),
  FOREIGN KEY (PARENT_ID) REFERENCES FA_PARENT(ID)
) ENGINE=InnoDB;

CREATE TABLE FA_GRANDPARENT (
  ID          BIGINT PRIMARY KEY,
  NAME        VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE FA_PARENT_H (
  ID              BIGINT PRIMARY KEY,
  GRANDPARENT_ID  BIGINT NOT NULL,
  NAME            VARCHAR(100),
  FOREIGN KEY (GRANDPARENT_ID) REFERENCES FA_GRANDPARENT(ID)
) ENGINE=InnoDB;

CREATE TABLE FA_CHILD_H (
  ID          BIGINT PRIMARY KEY,
  PARENT_ID   BIGINT NOT NULL,
  VALUE       VARCHAR(200),
  FOREIGN KEY (PARENT_ID) REFERENCES FA_PARENT_H(ID)
) ENGINE=InnoDB;

CREATE TABLE FA_COMPOSITE_PK (
  REGION      VARCHAR(10) NOT NULL,
  SEQ         BIGINT NOT NULL,
  DESCRIPTION VARCHAR(200),
  PRIMARY KEY (REGION, SEQ)
) ENGINE=InnoDB;
