package io.github.yok.flexdblink.core;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

/**
 * Immutable value object that holds the result of a dump operation.
 *
 * <p>
 * Stores the number of processed rows and the number of generated files during the dump.
 * </p>
 *
 * @author Yasuharu.Okawauchi
 */
@Getter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
public final class DumpResult {

    // Total number of rows output by the dump process
    private final int rowCount;

    // Total number of files generated by the dump process
    private final int fileCount;
}
