INSERT INTO IT_TYPED_MAIN (ID, VC_COL, CLOB_COL, NCLOB_COL, TINYBLOB_COL, MEDIUMBLOB_COL,
  LONGBLOB_COL, BLOB_COL, LOB_KIND)
VALUES (99, NULL, '', NULL, X'', X'', X'', X'', 'empty');

INSERT INTO IT_TYPED_AUX (ID, MAIN_ID, LABEL, PAYLOAD_CLOB, PAYLOAD_BLOB, LOB_KIND)
VALUES (99, 99, NULL, '', NULL, 'empty');
